name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    if: ${{ github.event_name == 'push' || (!contains(github.event.pull_request.title, 'DRAFT') && !contains(github.event.pull_request.title, 'Draft') && !contains(github.event.pull_request.title, 'draft') && !contains(github.event.pull_request.labels.*.name, 'draft')) }}
    runs-on: ubuntu-latest
    timeout-minutes: 40

    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run typecheck
        run: pnpm turbo typecheck

      - name: Run format:check
        run: pnpm turbo format:check

      - name: Run lint
        run: pnpm turbo lint

      - name: Run tests
        run: pnpm turbo test
